### ISSUE TITLE
不知道有没有补充以下信息的计划呢？

### ISSUE THREAD

**Issue by iou3344** [libredmm/librefanza#48]
中文标题 
系列 
男演员 
样图 
预览视频 
磁链 
如果可以补充上那就太完美了。

**Comment by libredmm** [comment]
谢谢反馈。

中文标题可以自行机器翻译，没有必要。
磁链涉及版权问题，不会添加。

其余的如果有官方信息来源后续可以考虑添加，其中样图可以确认是有的，其他的待确认。
